### ISSUE TITLE
Iterate array

### ISSUE THREAD

**Issue by psychok7** [artemrizhov/django-mail-templated#14]
Hello, is there a way i can iterate a list in my html email template?

i tried creating it before passing to the context as well with no luck:

```
        not_in_db_html = "<ul>"
        for db in sorted(not_in_db):
            not_in_db_html += "<li>" + db + "</li> "

        not_in_db_html += "</ul>"
```

it displays as a string in my email

**Comment by psychok7** [comment]
`{{ not_in_db | safe }}` fixed it for me. thanks anyways

**Comment by artemrizhov** [comment]
You can iterate lists as usually:
```python
send_mail('email/message.html',
          {'not_in_db': not_in_db},
          'from@inter.net', ['to@inter.net']
```
```html+django
{% extends "mail_templated/base.tpl" %}

{% block subject %}
Message with list
{% endblock %}

{% block html %}
    <ul>
        {% for db in not_in_db %}
            <li>{{ db }}</li>
        {% endfor %}
    </ul>
{% endblock %}
```

And btw, if you use filter `safe` then ensure the text is really safe:
```python
from django.utils.html import escape
...
not_in_db_html += "<li>" + escape(db) + "</li> "
```
But anyway embedding HTML into Python code is not a good idea usually. Use templates instead.

**Comment by psychok7** [comment]
@artemrizhov thanks. anyways i suggest this example get's added in the documentation. thanks again

**Comment by artemrizhov** [comment]
Thanks. Example is here :)
https://docs.djangoproject.com/en/dev/ref/templates/builtins/#for

**Comment by psychok7** [comment]
@artemrizhov i am trying to use this with attach file. can i attach_file with `send_mail` or it must be `message.send()` ? if its message.send() the email is now going empty for some reason

```
        message.attach_file('products_services/templates/email/digest.xls')
        message.send()
```

**Comment by artemrizhov** [comment]
Created new issue #15. Checking this now. Thanks for the report.

**Comment by artemrizhov** [comment]
@psychok7 Waiting for your response on #15. Not sure if you receive notifications from there.
