### ISSUE TITLE
No templates in the application package

### ISSUE THREAD

**Issue by artemrizhov** [artemrizhov/django-mail-templated#16]

**Comment by artemrizhov** [comment]
@psychok7 Should work now. Please update and try again.

**Comment by psychok7** [comment]
@artemrizhov everything is working fine now with version `django-mail-templated==2.4.3` . thanks.

by the way i would suggest you added your released versions Tags here on github also.

**Comment by artemrizhov** [comment]
@psychok7 
> i would suggest you added your released versions Tags here on github also

Done. Thanks for the suggestion.
