### ISSUE TITLE
Breaks for some template inheritance / extends

### ISSUE THREAD

**Issue by BradWhittington** [artemrizhov/django-mail-templated#2]
Hey, had the same issue with my lib (https://github.com/bradwhittington/django-templated-email/issues/3) with a caveated fix here - https://github.com/bradwhittington/django-templated-email/blob/867ef61693d02a39ca902a30e66d5dd7dd941cda/templated_email/utils.py

It breaks when you don't have blocks for subject/body/etc. in the template you render, but do have them in the template you extend

My solution is a messy hack, but after diving into the template code I couldn't find a better solution. Would love to see a neater, more comprehensive one (this breaks for {{block.super}})

**Comment by artemrizhov** [comment]
Fixed in new version.
