### ISSUE TITLE
RemovedInDjango110Warning when render with Context

### ISSUE THREAD

**Issue by fanshuai** [artemrizhov/django-mail-templated#20]
Hello, my django version is 1.9.2, when I send_mail with mail_templated has warning like this:

`
WARNING:py.warnings::/usr/local/lib/python2.7/dist-packages/mail_templated/message.py:174: RemovedInDjango110Warning: render() must be called with a dict, not a Context.
  result = self.template.render(context)
`

I know this does not affect to use, but if replace Context with dict is easy, I think it is a good idea for compatibility.

I love this package, thank you ~

**Comment by artemrizhov** [comment]
@fanshuai Thank you for your feedback!

I'll try to get rid of this message.

**Comment by artemrizhov** [comment]
Fixed in 2.6.1. Thank you for notifying me about this problem!

**Comment by fanshuai** [comment]
Nice, thank you ~
