### ISSUE TITLE
Can't send html, only plain works.

### ISSUE THREAD

**Issue by lomholdt** [artemrizhov/django-mail-templated#27]
It seems when i load a template with only `{% block html %}<strong>Text</strong>{% endblock %}` mail is sent as a text/plain message. Anyone having this issue?

Full template looks like this
```
{% extends 'mail_templated/base.tpl' %}

{% block subject %}
Din bruger på Klinikker.dk
{% endblock %}

{% block html %}
    <h1>Hello there</h1>
{% endblock %}
```

**Comment by lomholdt** [comment]
It seems to work if I define a body as well.

**Comment by artemrizhov** [comment]
Hi! Could you please run tests?

**Comment by artemrizhov** [comment]
@lomholdt Could you please run tests?

**Comment by artemrizhov** [comment]
Closing this issue because I can't reproduce this problem.
