### ISSUE TITLE
When create mesage - i take mistake. Django 1.11.7, Python 3.5

### ISSUE THREAD

**Issue by alexinc2000** [artemrizhov/django-mail-templated#31]
When i create message, i take mistake:
AttributeError at /
'NoneType' object has no attribute 'splitlines'
Request Method:	POST
Request URL:	http://127.0.0.1:8080/
Django Version:	1.11.7
Exception Type:	AttributeError
Exception Value:	
'NoneType' object has no attribute 'splitlines'
Exception Location:	/var/www/lf/lib/python3.5/site-packages/django/core/mail/message.py in set_payload, line 224
Python Executable:	/var/www/lf/bin/python
Python Version:	3.5.3
Python Path:	
['/var/www/lf/lFD',
 '/usr/lib/python35.zip',
 '/usr/lib/python3.5',
 '/usr/lib/python3.5/plat-x86_64-linux-gnu',
 '/usr/lib/python3.5/lib-dynload',
 '/var/www/lf/lib/python3.5/site-packages',
I take settings from docs. 
Is it incompatibility or Did i mistake anywhere?

**Comment by artemrizhov** [comment]
Hi! Could you please provide full example of code that does not work for you?

**Comment by alexinc2000** [comment]
Ok.
Tpl:
{% block subject %}
Hello {{ user }}
{% endblock %}

{% block body %}
Your task status is change.
{% endblock %}

{% block html %}
Your task status is change.
{% endblock %}


Code:
from django.conf import settings
from mail_templated import send_mail
#views
send_mail('email_template/email_task_status.tpl',{'user':'AS' }, settings.EMAIL_HOST_USER,['alexinc@alexinc.org'])

Settings file:
INSTALLED_APPS = [
'mail_templated'
]
EMAIL_USE_TLS = True
EMAIL_HOST = 'smtp.yandex.ru'
EMAIL_PORT = 587
EMAIL_HOST_USER = DEFAULT_FROM_EMAIL = 'support@lf.ru'
EMAIL_HOST_PASSWORD = '***********'
DEFAULT_CHARSET='utf-8'
SERVER_EMAIL = EMAIL_HOST_USER

That's all folks.
And i don't write into settings EMAIL_BACKEND. Is it need?

**Comment by artemrizhov** [comment]
Please try to extend the base template:

{% extends "mail_templated/base.tpl" %}

**Comment by artemrizhov** [comment]
If this does not help then could you please run tests for mail_templated?

**Comment by alexinc2000** [comment]
Very strange things - i add {% extends "mail_templated/base.tpl" %} and email is gone. But yastaday i take a mistake.
Ok. Now i close issue, 'couse problem is gone out.
Thank you for fast response.

**Comment by artemrizhov** [comment]
Please take into account that in the last version {% extends %} is required.
