### ISSUE TITLE
Add ability to compile the templated EmailMessage object into standard EmailMessage

### ISSUE THREAD

**Issue by artemrizhov** [artemrizhov/django-mail-templated#8]
`send_mail` function should compile messages by default. This should fix the serialization problem described in #7.

**Comment by ptwobrussell** [comment]
FWIW, I think I just got bitten by this when trying to use this package in combination with djcelery-email because the messages don't compile by default and a pickling error erupts. Serializing to avoid that would be quite helpful.

**Comment by jonashaag** [comment]
You might want to try my reimplementation https://github.com/jonashaag/django-mail-templated-simple

**Comment by ptwobrussell** [comment]
Looks great, thanks!

**Comment by jonashaag** [comment]
Sorry for resurrecting this old issue. It just wanted to let @ptwobrussell know that django-mail-templated-simple is now a properly tested and installable project.

**Comment by ptwobrussell** [comment]
Thanks!

**Comment by artemrizhov** [comment]
@jonashaag @ptwobrussell 
Just letting you know that the latest version should not have any issues with serialization. It also supports the template inheritance as is. The app is much more stable now. All features will be described in the documentation that I will publish soon.
